import { useQuery } from '@tanstack/react-query'
import { ClaimsAssistant } from '../../components/ClaimsAssistant'
import { api } from '../../api/client'
import type { ClaimDetail as Detail } from '../../types/claims'
import { Status, money, humanize } from '../../components/Status'
function ruleDescription(code: string, parameters: Record<string, unknown>, currency: string) {
  if (code === 'amount_limit') return `Maximum ${money(String(parameters.maximum), currency)}`
  if (code === 'receipt_required') return parameters.required ? 'Verified receipt for every line' : 'Receipt optional'
  if (code === 'allowed_category') return (parameters.categories as string[]).join(', ')
  if (code === 'date_validity') return `Submit within ${parameters.maximum_age_days} days`
  return code
}
export function ClaimFacts({claim}: {claim: Detail}) {
  const findings=claim.findings.filter(f=>f.claim_version===claim.assessment?.claim_version || (!claim.assessment && f.claim_version===claim.version))
  return <><section className="panel"><h2>Source facts</h2><div className="facts"><div><span>Employee</span><strong>{claim.employee.name}</strong><small>{claim.employee.department} · {claim.employee.email}</small></div><div><span>Submitted</span><strong>{claim.submitted_date}</strong><small>{claim.claim_type} · Version {claim.version}</small></div><div><span>Claim amount</span><strong>{money(claim.amount,claim.currency)}</strong></div></div><div className="table-scroll"><table><thead><tr><th>Description</th><th>Category</th><th>Expense date</th><th>Amount</th></tr></thead><tbody>{claim.lines.map(line=><tr key={line.id}><td>{line.description}</td><td>{line.category}</td><td>{line.expense_date}</td><td>{money(line.amount,claim.currency)}</td></tr>)}</tbody></table></div></section>
  <div className="two-columns"><section className="panel"><h2>Applicable policy</h2><h3>{claim.policy.name}</h3><p>{claim.policy.text}</p><div className="policy-rules">{claim.policy.rules.map(rule=><div key={rule.id}><strong>{humanize(rule.code)}</strong><span>{ruleDescription(rule.code, rule.parameters, claim.policy.currency)}</span></div>)}</div><small>Automatic acceptance: {claim.policy.auto_accept?'allowed':'disabled'} · Automatic rejection: {claim.policy.auto_reject?'allowed':'disabled'}</small></section><section className="panel"><h2>Evidence</h2>{claim.evidence.length?claim.evidence.map(e=><article className="evidence" key={e.id}><strong>{e.filename}</strong><Status value={e.verified?'verified':'unverified'}/><p>{e.content}</p><small>Reference: {e.id}</small></article>):<p className="empty">No supporting evidence supplied.</p>}</section></div>
  <section className="panel"><h2>Deterministic policy findings</h2>{findings.length?findings.map(f=><div className="finding" key={f.id}><Status value={f.severity}/><div><strong>{humanize(f.code)}</strong><p>{f.message}</p></div></div>):<p className="muted">Checks run before AI interpretation when the batch assesses this claim.</p>}</section>
  <section className="panel"><h2>AI assessment</h2>{claim.assessment?<><div className="assessment-heading"><Status value={claim.assessment.data.recommendation}/><span>{Math.round(claim.assessment.data.confidence*100)}% confidence · Claim version {claim.assessment.claim_version}</span></div><p>{claim.assessment.data.explanation}</p><p className="muted">Finding references: {claim.assessment.data.findings.join(', ')}</p><p className="muted">Evidence references: {claim.assessment.data.evidence_ids.join(', ') || 'None'}</p>{claim.assessment.data.unresolved_questions.length>0 && <><h3>Unresolved questions</h3><ul>{claim.assessment.data.unresolved_questions.map(q=><li key={q}>{q}</li>)}</ul></>}</>:<p className="muted">No validated assessment yet.</p>}</section></>
}
export function ProcessingHistory({claim}: {claim: Detail}) {return <section className="panel"><h2>Audit & processing history</h2>{claim.history.length?<ol className="history">{claim.history.map(event=><li key={event.id}><strong>{humanize(event.event_type)}</strong><span>{event.actor} · {new Date(event.created_at).toLocaleString()}</span><small>Run {event.run_id}</small><details><summary>Event details</summary><pre>{JSON.stringify(event.data,null,2)}</pre></details></li>)}</ol>:<p className="muted">No processing events yet.</p>}{claim.executions.map(e=><div className="execution" key={e.id}><Status value={e.status}/><span>{e.provider} / {e.model} · {e.duration_ms} ms {e.error_code && `· ${e.error_code}`}</span><small>{e.trajectory.join(' → ')}</small></div>)}</section>}
export function ClaimDetail({id}: {id:string}) {
  const query=useQuery({queryKey:['claim',id],queryFn:()=>api.claim(id),refetchInterval:q=>q.state.data?.status==='submitted'?2000:false})
  const memory=useQuery({queryKey:['memory',id],queryFn:()=>api.memory(id)})
  if(query.isPending)return <p role="status">Loading claim…</p>
  if(query.error)return <p role="alert">{query.error.message}</p>
  const claim=query.data
  return <><a className="back" href="#/claims">← Claim queue</a><div className="page-heading"><div><p className="eyebrow">{claim.id}</p><h1>{claim.title}</h1><Status value={claim.status}/></div><div className="actions">{claim.review && <a className="action-link" href={`#/reviews/${claim.review.id}`}>Open manager review</a>}</div></div>{claim.status==='submitted' && <div className="action-feedback pending"><strong>Awaiting batch assessment</strong><p>Run assessments from the claim queue. Results appear here automatically.</p><a href="#/claims">Go to batch controls →</a></div>}<ClaimsAssistant claimId={id} embedded/><ClaimFacts claim={claim}/>
  {claim.outcome && <section className="panel"><h2>Recorded outcome</h2><Status value={claim.outcome.final_decision}/><p>{claim.outcome.reviewer_rationale || 'Automatically executed within policy controls.'}</p><small>{claim.outcome.reviewed?'Reviewed outcome available to enterprise memory.':'Automatic outcome; excluded from reviewed memory retrieval.'}</small></section>}
  <section className="panel"><h2>Enterprise memory</h2>{memory.isPending?<p>Loading reviewed outcomes…</p>:memory.error?<p role="alert">{memory.error.message}</p>:memory.data?.length?memory.data.map(o=><article key={o.id}><a href={`#/claims/${o.claim_id}`}>{o.claim_id}</a> · <Status value={o.final_decision}/><p>{o.reviewer_rationale}</p></article>):<p className="muted">No relevant previously reviewed outcomes.</p>}</section><ProcessingHistory claim={claim}/></>
}
