import { test, expect } from '@playwright/test'
test('accept, reject, investigate, manager review and outcome',async({page})=>{
 await page.goto('/')
 await expect(page.getByRole('heading',{name:'Claim queue',exact:true})).toBeVisible()
 await page.getByRole('link',{name:/CLM-001/}).click()
 await page.getByRole('button',{name:'Assess & process'}).click()
 await expect(page.getByText('accepted',{exact:true}).first()).toBeVisible()
 await page.getByRole('link',{name:'← Claim queue'}).click()
 await page.getByRole('link',{name:/CLM-002/}).click()
 await page.getByRole('button',{name:'Assess & process'}).click()
 await expect(page.getByText('rejected',{exact:true}).first()).toBeVisible()
 await page.getByRole('link',{name:'← Claim queue'}).click()
 await page.getByRole('link',{name:/CLM-003/}).click()
 await page.getByRole('button',{name:'Assess & process'}).click()
 await expect(page.getByText('pending manager review',{exact:true})).toBeVisible()
 await page.getByRole('link',{name:'Open manager review'}).click()
 await expect(page.getByRole('heading',{name:'Investigation reason'})).toBeVisible()
 await page.getByLabel('Reviewer rationale').fill('Original taxi receipt checked with employee; expense verified.')
 await page.getByRole('button',{name:'Accept',exact:true}).click()
 await expect(page.getByText('This review is closed.')).toBeVisible()
 await page.getByRole('link',{name:'View claim',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Recorded outcome'})).toBeVisible()
 await expect(page.getByText('Reviewed outcome available to enterprise memory.')).toBeVisible()
 await expect(page.getByText('manager decision recorded',{exact:true})).toBeVisible()
 await page.screenshot({path:'test-results/claim-outcome.png',fullPage:true})
})
