import { test, expect } from '@playwright/test'

test('Week 2: seven recommendations, every expense decided by a manager', async ({ page }) => {
  test.setTimeout(180000)
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Claim queue', exact: true })).toBeVisible()
  // Hold submission briefly to verify the busy control even with a fast mock model.
  await page.route('**/api/jobs/assess', async route => {
    await new Promise(resolve => setTimeout(resolve, 500))
    await route.continue()
  })
  await page.getByRole('button', { name: 'Run', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Running', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Finished', exact: true })).toBeVisible({ timeout: 120000 })
  await expect(page.getByText('7 of 7 assessments finished.')).toBeVisible()
  await page.screenshot({ path: 'test-results/batch-finished.png', fullPage: true })
  await page.reload()
  await expect(page.getByRole('button', { name: 'Finished', exact: true })).toBeVisible()
  await expect(page.getByText('0 running · 0 queued')).toBeVisible()
  const claims = await (await page.request.get('/api/claims')).json()
  expect(claims).toHaveLength(7)
  expect(claims.every((claim: {status:string}) => claim.status === 'pending_manager_review')).toBe(true)
  await page.getByRole('link', { name: /CLM-001 Client lunch/ }).click()
  await expect(page.locator('.page-heading').getByText('pending manager review', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Assess & process' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Ask about this claim' })).toBeVisible()
  await page.getByRole('link', { name: '← Claim queue' }).click()
  await page.getByRole('link', { name: /CLM-002 Personal entertainment/ }).click()
  await expect(page.locator('.page-heading').getByText('pending manager review', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '← Claim queue' }).click()
  await page.getByRole('link', { name: /CLM-003 Airport taxi/ }).click()
  await expect(page.locator('.page-heading').getByText('pending manager review', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'What evidence is missing?' }).click()
  await expect(page.getByRole('log')).toContainText(/receipt/i, { timeout: 60000 })
  await page.screenshot({ path: 'test-results/claim-chat.png', fullPage: true })
  await page.getByRole('link', { name: 'Open manager review' }).click()
  await expect(page.getByRole('heading', { name: 'AI recommendation' })).toBeVisible()
  await expect(page.getByRole('button', {name: 'Request information'})).toHaveCount(0)
  await page.getByLabel('Reviewer rationale').fill('Original taxi receipt checked with employee; expense verified.')
  await page.getByRole('button', { name: 'Accept', exact: true }).click()
  await expect(page.getByText(/Manager decision recorded. Claim accepted/)).toBeVisible()
  await expect(page.getByText('This review is closed.')).toBeVisible()
  await page.getByRole('link', { name: 'View claim', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Recorded outcome' })).toBeVisible()
  await expect(page.getByText('Reviewed outcome available to enterprise memory.')).toBeVisible()
  await expect(page.getByText('manager decision recorded', { exact: true })).toBeVisible()
  await page.getByRole('link', {name:'← Claim queue'}).click()
  await page.getByRole('link', {name:/CLM-001 Client lunch/}).click()
  await page.getByRole('link', {name:'Open manager review'}).click()
  await page.getByLabel('Reviewer rationale').fill('Manager declines this expense despite the AI acceptance recommendation.')
  await page.getByRole('button', {name:'Reject',exact:true}).click()
  await expect(page.getByText(/Manager decision recorded. Claim rejected/)).toBeVisible()
})
